homeassistant:
  customize:
    sensor.adjusted_solcast_total_forecast_today:
      friendly_name: "Adjusted Total Solar Forecast Today"
      icon: mdi:weather-sunny
    sensor.adjusted_solcast_remaining_forecast_today:
      friendly_name: "Adjusted Remaining Solar Forecast Today"
      icon: mdi:weather-sunny
    sensor.adjusted_solcast_power_next_hour:
      friendly_name: "Adjusted Solar Power Next Hour"
      icon: mdi:flash
    sensor.adjusted_solcast_power_next_30_mins:
      friendly_name: "Adjusted Solar Power Next 30 Minutes"
      icon: mdi:flash
    sensor.dynamic_charging_rate:
      friendly_name: "Dynamic Charging Rate"
      icon: mdi:battery-charging
    sensor.required_charging_time:
      friendly_name: "Required Charging Time"
      icon: mdi:timer
    sensor.remaining_capacity:
      friendly_name: "Remaining Battery Capacity"
      icon: mdi:battery
    sensor.optimal_start_time:
      friendly_name: "Optimal Charging Start Time"
      icon: mdi:clock-start
    sensor.current_time:
      friendly_name: "Current Time"
      icon: mdi:clock
    sensor.charging_condition:
      friendly_name: "Charging Condition Met"
      icon: mdi:check-circle
    sensor.forecast_remaining:
      friendly_name: "Forecast Remaining"
      icon: mdi:weather-sunny
    sensor.required_energy:
      friendly_name: "Required Energy"
      icon: mdi:battery
    sensor.adjusted_required_energy:
      friendly_name: "Adjusted Required Energy"
      icon: mdi:battery-alert

input_number:
  solar_dampener:
    name: Solar Dampener
    initial: 100
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
    icon: mdi:weather-sunny

input_boolean:
  charging_in_progress:
    name: Charging in Progress
    initial: off

sensor:
  - platform: template
    sensors:
      # Adjusted Solcast Forecast for Today based on the Solar Dampener
      adjusted_solcast_total_forecast_today:
        friendly_name: "Adjusted Solcast Total Forecast Today"
        unit_of_measurement: 'kWh'
        value_template: >
          {% set forecast = states('sensor.solcast_pv_forecast_forecast_today')|float(0) %}
          {% set dampener = states('input_number.solar_dampener')|float(0) / 100 %}
          {{ forecast * dampener }}

      # Adjusted Solcast Remaining Forecast for Today based on the Solar Dampener
      adjusted_solcast_remaining_forecast_today:
        friendly_name: "Adjusted Solcast Remaining Forecast Today"
        unit_of_measurement: 'kWh'
        value_template: >
          {% set forecast = states('sensor.solcast_pv_forecast_forecast_remaining_today')|float(0) %}
          {% set dampener = states('input_number.solar_dampener')|float(0) / 100 %}
          {{ forecast * dampener }}

      # Adjusted Solcast Power for the Next Hour based on the Solar Dampener
      adjusted_solcast_power_next_hour:
        friendly_name: "Adjusted Solcast Power Next Hour"
        unit_of_measurement: 'W'
        value_template: >
          {% set forecast = states('sensor.solcast_pv_forecast_power_next_hour')|float(0) %}
          {% set dampener = states('input_number.solar_dampener')|float(0) / 100 %}
          {{ forecast * dampener }}

      # Adjusted Solcast Power for the Next 30 Minutes based on the Solar Dampener
      adjusted_solcast_power_next_30_mins:
        friendly_name: "Adjusted Solcast Power Next 30 Mins"
        unit_of_measurement: 'W'
        value_template: >
          {% set forecast = states('sensor.solcast_pv_forecast_power_next_30_mins')|float(0) %}
          {% set dampener = states('input_number.solar_dampener')|float(0) / 100 %}
          {{ forecast * dampener }}

      # Dynamic Charging Rate based on Battery Temperature
      dynamic_charging_rate:
        friendly_name: "Dynamic Charging Rate"
        unit_of_measurement: 'kW'
        value_template: >
          {% set base_rate = 8.192 %}
          {% set temp = states('sensor.alpha_ess_battery_min_cell_temp_2')|float(0) %}
          {% if temp > 40 %}
            {{ [base_rate - ((temp - 40) * 0.25), 0]|max }}
          {% elif temp < 0 %}
            {{ [base_rate - (abs(temp) * 0.4), 0]|max }}
          {% else %}
            {{ base_rate }}
          {% endif %}

      # Required Energy to Fully Charge the Battery
      required_energy:
        friendly_name: "Required Energy"
        unit_of_measurement: 'kWh'
        value_template: >
          {% set soc = states('sensor.alpha_ess_soc_battery')|float(0) %}
          {{ (100 - soc) / 100 * 15.6 }}

      # Required Charging Time based on Required Energy and Dynamic Charging Rate
      required_charging_time:
        friendly_name: "Required Charging Time"
        unit_of_measurement: 'hours'
        value_template: >
          {% set required_energy = states('sensor.required_energy')|float(0) %}
          {% set dynamic_rate = states('sensor.dynamic_charging_rate')|float(0) %}
          {% set forecast_remaining = states('sensor.adjusted_solcast_remaining_forecast_today')|float(0) %}
          {% if forecast_remaining < required_energy %}
            {% set required_time = required_energy / dynamic_rate %}
            {{ required_time + 1 }}  # Adding 1 hour buffer
          {% else %}
            {% set required_time = required_energy / dynamic_rate %}
            {{ required_time }}
          {% endif %}

      # Adjusted Required Energy after accounting for Solar Forecast
      adjusted_required_energy:
        friendly_name: "Adjusted Required Energy"
        unit_of_measurement: 'kWh'
        value_template: >
          {% set required_energy = states('sensor.required_energy')|float(0) %}
          {% set forecast_remaining = states('sensor.adjusted_solcast_remaining_forecast_today')|float(0) %}
          {{ required_energy - forecast_remaining }}

      # Remaining Battery Capacity in kWh
      remaining_capacity:
        friendly_name: "Remaining Capacity"
        unit_of_measurement: 'kWh'
        value_template: >
          {% set soc = states('sensor.alpha_ess_soc_battery')|float(0) %}
          {{ 15.6 * (soc / 100) }}

      # Optimal Start Time for Charging based on Required Charging Time
      optimal_start_time:
        friendly_name: "Optimal Start Time"
        value_template: >
          {% set required_time = states('sensor.required_charging_time')|float(0) %}
          {% set optimal_time = 16 - required_time %}
          {% set hours = optimal_time|int %}
          {% set minutes = ((optimal_time - hours) * 60)|int %}
          {{ '%02d:%02d' % (hours, minutes) }}

      # Current Time in HH:MM format
      current_time:
        friendly_name: "Current Time"
        value_template: >
          {% set hours = now().hour %}
          {% set minutes = now().minute %}
          {{ '%02d:%02d' % (hours, minutes) }}

      # Condition to Check if Charging is Needed
      charging_condition:
        friendly_name: "Charging Condition"
        value_template: >
          {% set soc = states('sensor.alpha_ess_soc_battery')|float(0) %}
          {% set remaining_capacity = 15.6 * (1 - soc / 100) %}
          {% set forecast_remaining = states('sensor.adjusted_solcast_remaining_forecast_today')|float(0) %}
          {% set next_hour_power = states('sensor.adjusted_solcast_power_next_hour')|float(0) %}
          {% set next_30min_power = states('sensor.adjusted_solcast_power_next_30_mins')|float(0) %}
          {% set required_time = states('sensor.required_charging_time')|float(0) %}
          {% set now_time = now().hour + now().minute / 60 %}
          {% set end_time = 16 %}
          {% set optimal_start_time = end_time - required_time %}
          {{ (remaining_capacity > 0 and (forecast_remaining >= remaining_capacity or soc < 100) and (next_hour_power > 0 or next_30min_power > 0) and now_time >= optimal_start_time) or is_state('input_boolean.charging_in_progress', 'on') }}

      # Forecast Remaining Energy for Today
      forecast_remaining:
        friendly_name: "Forecast Remaining"
        unit_of_measurement: 'kWh'
        value_template: "{{ states('sensor.adjusted_solcast_remaining_forecast_today')|float(0) }}"

binary_sensor:
  - platform: template
    sensors:
      # Binary Sensor to Indicate if Battery is Charging
      battery_charging:
        friendly_name: "Battery Charging"
        value_template: >
          {{ states('sensor.alpha_ess_power_battery')|float(0) < 0 }}
        icon_template: >
          {% if is_state('binary_sensor.battery_charging', 'on') %}
            mdi:battery-charging
          {% else %}
            mdi:battery
          {% endif %}

automation:
  # Manage Battery Charging Automation
  - alias: Manage Battery Charging
    trigger:
      # Trigger Every 10 Minutes
      - platform: time_pattern
        minutes: "/10"
      # Trigger When Battery SOC Changes
      - platform: state
        entity_id: sensor.alpha_ess_soc_battery
      # Trigger When Adjusted Solar Forecast Changes
      - platform: state
        entity_id: sensor.adjusted_solcast_remaining_forecast_today
      # Trigger When Battery Temperature Changes
      - platform: state
        entity_id: sensor.alpha_ess_battery_min_cell_temp_2
      # Trigger When Solar Dampener Changes
      - platform: state
        entity_id: input_number.solar_dampener
    condition:
      condition: and
      conditions:
        # Check if Charging Condition is Met
        - condition: template
          value_template: >
            {% set soc = states('sensor.alpha_ess_soc_battery')|float(0) %}
            {% set remaining_capacity = 15.6 * (1 - soc / 100) %}
            {% set forecast_remaining = states('sensor.adjusted_solcast_remaining_forecast_today')|float(0) %}
            {% set next_hour_power = states('sensor.adjusted_solcast_power_next_hour')|float(0) %}
            {% set next_30min_power = states('sensor.adjusted_solcast_power_next_30_mins')|float(0) %}
            {% set required_time = states('sensor.required_charging_time')|float(0) %}
            {% set now_time = now().hour + now().minute / 60 %}
            {% set end_time = 16 %}
            {% set optimal_start_time = end_time - required_time %}
            {{ (remaining_capacity > 0 and (forecast_remaining >= remaining_capacity or soc < 100) and (next_hour_power > 0 or next_30min_power > 0) and now_time >= optimal_start_time) or is_state('input_boolean.charging_in_progress', 'on') }}
    action:
      - delay: '00:00:05'
      # Turn On Charging in Progress Indicator
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.charging_in_progress
      # Debug Information
      - service: persistent_notification.create
        data:
          title: "Battery Charging Debug"
          message: >
            SOC: {{ states('sensor.alpha_ess_soc_battery') }}
            Remaining Capacity: {{ 15.6 * (1 - (states('sensor.alpha_ess_soc_battery')|float(0) / 100)) }}
            Forecast Remaining: {{ states('sensor.adjusted_solcast_remaining_forecast_today') }}
            Next Hour Power: {{ states('sensor.adjusted_solcast_power_next_hour') }}
            Next 30 Min Power: {{ states('sensor.adjusted_solcast_power_next_30_mins') }}
            Required Charging Time: {{ states('sensor.required_charging_time') }}
            Adjusted Required Energy: {{ states('sensor.adjusted_required_energy') }}
            Current Time: {{ states('sensor.current_time') }}
            Optimal Start Time: {{ states('sensor.optimal_start_time') }}
            Charging In Progress: {{ states('input_boolean.charging_in_progress') }}

      # Send Modbus Commands to Start Charging
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2133
          slave: !secret alphaess_modbus_slaveId
          value: 100

      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2134
          slave: !secret alphaess_modbus_slaveId
          value: 10

      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2135
          slave: !secret alphaess_modbus_slaveId
          value: 16

      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2136
          slave: !secret alphaess_modbus_slaveId
          value: 0

      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2137
          slave: !secret alphaess_modbus_slaveId
          value: 0

      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2142
          slave: !secret alphaess_modbus_slaveId
          value: 0

      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2143
          slave: !secret alphaess_modbus_slaveId
          value: 0

  # Stop Battery Charging Automation at 16:00
  - alias: Stop Battery Charging
    trigger:
      - platform: time
        at: '16:00:00'
    action:
      # Turn Off Charging in Progress Indicator
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.charging_in_progress
      # Send Modbus Commands to Stop Charging
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2133
          slave: !secret alphaess_modbus_slaveId
          value: 0
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2134
          slave: !secret alphaess_modbus_slaveId
          value: 0
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2135
          slave: !secret alphaess_modbus_slaveId
          value: 0
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2136
          slave: !secret alphaess_modbus_slaveId
          value: 0
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2137
          slave: !secret alphaess_modbus_slaveId
          value: 0
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2142
          slave: !secret alphaess_modbus_slaveId
          value: 1
      - service: modbus.write_register
        data:
          hub: modbuspvsystem
          address: 2143
          slave: !secret alphaess_modbus_slaveId
          value: 1
