
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages
  
template:
  - sensor:
      - name: "Electricity Tariff"
        state: >
            {% if today_at('17:00') <= now() < today_at('21:00') %} 
            peak_rate
            {% elif today_at('10:00') <= now() < today_at('16:00') %}
            off_peak_rate 
            {% elif today_at('06:00') <= now() < today_at('09:00') %}
            sholder1
            {% else %}
            sholder2
            {% endif %}
logger:
  default: info
  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug
python_script:    